# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool: 
  name: Default

variables:
  solution: '**/StringExtensionsBspmLibrary.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: '1'
  minor: '2'
  revision: $[counter('', 100)]

  # Build.BuildNumber
name: '$(major).$(minor).$(revision)'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.x'
  inputs:
    packageType: sdk
    version: 3.x

# Nuget
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

# Restore Nuget
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/StringExtensionsBspmLibrary.sln'
    feedsToUse: 'select'
    vstsFeed: '7d4fb428-f204-4d3e-a647-c8b5439e541e'

# Build StringExtensionsBspmLibrary.sln
- task: VSBuild@1
  displayName: 'Build StringExtensions'
  inputs:
    solution: '**/StringExtensionsBspmLibrary.sln'
    msbuildArgs: '/clp:ErrorsOnly'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Publish to Artifact 'drop'
#- task: PublishBuildArtifacts@1
#  displayName: Publish Artifact to Drop
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#    ArtifactName: 'drop'
#    publishLocation: 'Container'

# Package a project
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensionsBspmLibrary.csproj'
    versioningScheme: byBuildNumber
    majorVersion: '$(major)'
    minorVersion: '$(minor)'
    patchVersion: '$(revision)'
    

# Push a project
- task: NuGetCommand@2
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'sophieschorochoff'
